#!/usr/bin/env bash
# cmake -G "Ninja" -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -Wdev $@
cmake -G "Ninja" -S . -B ./build \
    -Wdev \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_COMPILER=$(which clang++) \
    -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always \
    $@
