#!/usr/bin/env bash
set -euo pipefail

usage="Usage: $0 <packages>

Installs Qt 6.6.1 to 3rdparty/Qt. For this script to work, you need to set the 
QT_INSTALLER_JWT_TOKEN environment variable to your jwt token. Check the
website of Qt for more information.

Optionally, you can add more Qt packages to install by adding them as
arguments.

Options:
  -r, --root    The root directory to install Qt to.
  -h, --help    Show this help message and exit"

this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
packages=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -r | --root)
            install_dir="$2"
            shift
            shift
            ;;
        -h | --help)
            echo "$usage"
            exit 0
            ;;
        *)
            packages="$packages $1"
            shift
            ;;
    esac
done
"$this_dir/qt-installer.run" --root "$install_dir" --accept-licenses --accept-obligations --default-answer --confirm-command install $packages
