#!/usr/bin/env bash
set -euo pipefail

echo "Installing deps instead of compiling from source"
sudo apt install nasm libx264-dev libx265-dev libnuma-dev libvpx-dev libfdk-aac-dev libopus-dev libdav1d-dev -y
