#!/usr/bin/env bash
set -euo pipefail

usage="Usage: install-vulkan

Used when running apt package manager to install vulkan sdk using a PPA
repository"

this_dir=$(dirname "$(realpath "${BASH_SOURCE:-$0}")")
"$this_dir/assert"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h | --help)
            echo "$usage"
            exit 0
            ;;
    esac
done

echo "Adding PPA repository for vulkan sdk"
wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install vulkan-sdk
