#!/usr/bin/env bash
sudo pacman -S --noconfirm \
    aarch64-linux-gnu-gcc \
    aarch64-linux-gnu-glibc \
    aarch64-linux-gnu-binutils \
    aarch64-linux-gnu-gdb \
    aarch64-linux-gnu-linux-api-headers \
    rsync

sudo yay -S --noconfirm simlinks || echo "You need to install the AUR package 'symlinks' manually"
