#!/usr/bin/env bash
set -euo pipefail

echo "Installing build tools and dependencies"
sudo pacman -S --noconfirm autoconf automake cmake git libass freetype2 sdl2 libtool libvdpau libvorbis libxcb meson ninja pkgconf texinfo wget yasm gnutls libunistring tar
sudo pacman -S --noconfirm zlib

echo "Installing ffmpeg dependencies"
sudo pacman -S --noconfirm numactl libdrm libva numactl
