#!/bin/env bash
set -euo pipefail

usage="$(basename "$0") [-h] -- Compiles libva from source and 
installs it to <prefix>. The libraries will be installed to <prefix>/lib. If 
the prefix is not provided, the script will exit.

The packages managers \`apt\` and \`pacman\` are supported.

where:
    -h, --help          show this help text
    -s, --source-dir    source directory (default: ./libva)
    -p, --prefix        the prefix to install libva to (default: /usr)"

src="./libva"
prefix="/usr"
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h | --help)
            echo "$usage"
            exit
            ;;
        -s | --source-dir)
            src="$2"
            shift
            shift
            ;;
        *)
            prefix="$key"
            shift
            ;;
    esac
done

if [[ -z "$prefix" ]]; then
    echo "Prefix cannot be empty"
    echo "$usage"
    exit 1
fi

src=$(realpath "$src")
prefix=$(realpath "$prefix")

install_deps() {
    echo "Installing dependencies"
    if command -v apt-get &>/dev/null; then
        echo "apt-get found"
        remove_libva_apt
        install_deps_apt
    elif command -v pacman &>/dev/null; then
        echo "pacman found"
        remove_libva_pacman
        install_deps_pacman
    else
        echo "No supported package manager found"
        exit 1
    fi
}

remove_libva_apt() {
    echo "Removing libva"
    sudo dpkg --remove --force-depends libva-dev || true
    sudo dpkg --remove --force-depends libva2 || true
}

install_deps_apt() {
    echo "Installing apt dependencies"
    sudo apt-get -y install autogen automake cmake git libtool libwayland-dev libx11-dev libx11-xcb-dev libx11-xcb-perl libx11-xcb1 libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb1-dev libxext-dev libxfixes-dev meson pkg-config xorg-dev || true
}

remove_libva_pacman() {
    echo "Removing libva"
    sudo pacman -R --noconfirm -dd libva || true
}

install_deps_pacman() {
    echo "Installing pacman dependencies"
    sudo pacman -S --noconfirm git cmake pkg-config meson automake libtool autogen xorg wayland libxext libxfixes || true
}

build_libva() {
    dir=$(pwd)
    echo "Removing path: $src"
    rm -rf "$src"
    echo "Cd to base dir $(dirname "$src")"
    cd "$(dirname "$src")"
    echo "Cloning libva with output dir: $(basename "$src")"
    git clone https://github.com/intel/libva.git "$(basename "$src")"
    echo "Cd into: $src"
    cd "$src"
    ./autogen.sh --prefix="$prefix" --libdir="$prefix/lib"
    make
    sudo make install
    cd "$dir"
}

check() {
    echo "Checking libva"
    if ! pkg-config --exists libva libva-drm libva-x11 libva-wayland; then
        echo "One of the following packages is missing: libva, libva-drm, libva-x11, libva-wayland"
        exit 1
    else
        echo "libva, libva-drm, libva-x11, and libva-wayland are installed"
    fi
}

install_deps
build_libva
check
