#!/usr/bin/env bash
set -euo pipefail

this_dir=$(dirname "$(realpath "${BASH_SOURCE:-$0}")")
root="$(dirname "$this_dir")"
static=true
shared=false
source_dir="$root/ffmpeg_sources"
install_dir="$this_dir/../3rdparty/ffmpeg"

usage="$(basename "$0") [-h] [-s, --source-dir] [-b, --install-dir] --
Compiles ffmpeg from source.

The packages managers \`apt\` and \`pacman\` are supported.

where:
    -h, --help          show this help text
    --static            build static libraries (default: true)
    --shared            build shared libraries (default: false)
    -s, --source-dir    ffmpeg source directory (default: $source_dir)
    -i, --install-dir   ffmpeg build directory (default: $install_dir)"

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h | --help)
            echo "$usage"
            exit
            ;;
        --static)
            static=true
            shared=false
            shift
            ;;
        --shared)
            shared=true
            static=false
            shift
            ;;
        -s | --source-dir)
            source_dir="$2"
            shift
            shift
            ;;
        -i | --install-dir)
            install_dir="$2"
            shift
            shift
            ;;
        *)
            echo "Unknown option: $key"
            echo "$usage"
            exit 1
            ;;
    esac
done

bin_dir="$install_dir/bin"

install_dependencies() {
    manager="$("$this_dir/helpers/get-package-manager")"
    "${this_dir}/helpers/${manager}/install-ffmpeg-deps"
}

compile_nasm() {
    cd "$source_dir" &&
        wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2 &&
        tar xjvf nasm-2.16.01.tar.bz2 &&
        cd nasm-2.16.01 &&
        ./autogen.sh &&
        PATH="$bin_dir:$PATH" ./configure --prefix="$install_dir" --bindir="$bin_dir" &&
        make &&
        make install
}

compile_x264() {
    cd "$source_dir" &&
        git -C x264 pull 2>/dev/null || git clone https://code.videolan.org/videolan/x264.git &&
        cd x264 &&
        PATH="$bin_dir:$PATH" PKG_CONFIG_PATH="$install_dir/lib/pkgconfig" ./configure --prefix="$install_dir" --bindir="$bin_dir" --enable-static --enable-pic &&
        PATH="$bin_dir:$PATH" make &&
        make install
}

compile_x265() {
    cd "$source_dir" &&
        wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/Release_3.5.tar.bz2 &&
        tar xjvf x265.tar.bz2 &&
        cd multicoreware*/build/linux &&
        PATH="$bin_dir:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$install_dir" -DENABLE_SHARED=off ../../source &&
        PATH="$bin_dir:$PATH" make &&
        make install
}

compile_libvpx() {
    cd "$source_dir" &&
        git -C libvpx pull 2>/dev/null || git clone https://chromium.googlesource.com/webm/libvpx.git &&
        cd libvpx &&
        PATH="$bin_dir:$PATH" ./configure --prefix="$install_dir" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm &&
        PATH="$bin_dir:$PATH" make &&
        make install
}

compile_fdk-aac() {
    cd "$source_dir" &&
        PATH="$bin_dir:$PATH" &&
        git -C fdk-aac pull 2>/dev/null || git clone https://github.com/mstorsjo/fdk-aac &&
        cd fdk-aac &&
        autoreconf -fiv &&
        ./configure --prefix="$install_dir" --disable-shared &&
        make &&
        make install
}

compile_libopus() {
    cd "$source_dir" &&
        PATH="$bin_dir:$PATH" &&
        git -C opus pull 2>/dev/null || git clone https://github.com/xiph/opus.git &&
        cd opus &&
        ./autogen.sh &&
        ./configure --prefix="$install_dir" --disable-shared &&
        make &&
        make install
}

compile_libdav1d() {
    cd "$source_dir" &&
        PATH="$bin_dir:$PATH" &&
        git -C dav1d pull 2>/dev/null || git clone https://code.videolan.org/videolan/dav1d.git &&
        cd dav1d &&
        mkdir -p build &&
        cd build &&
        meson setup -Denable_tools=false -Denable_tests=false --default-library=static .. --prefix "$install_dir" --libdir="$install_dir/lib" &&
        ninja &&
        ninja install
}

compile_libaom() {
    echo "Compiling libaom"
    cd "$source_dir" &&
        git -C aom pull 2>/dev/null || git clone https://aomedia.googlesource.com/aom &&
        cd aom &&
        cd - &&
        mkdir -p aom_build &&
        cd aom_build &&
        PATH="$bin_dir:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$install_dir" -DENABLE_TESTS=OFF -DENABLE_NASM=on ../aom &&
        PATH="$bin_dir:$PATH" make -j"$(nproc)" &&
        make install
}

compile_libsvtav1() {
    echo "Compiling libsvtav1"
    cd "$source_dir" &&
        git -C SVT-AV1 pull 2>/dev/null || git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git &&
        cd SVT-AV1 &&
        mkdir -p build &&
        cd build &&
        PATH="$bin_dir:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_BUILD_TYPE=Release -DBUILD_DEC=OFF -DBUILD_SHARED_LIBS=OFF .. &&
        PATH="$bin_dir:$PATH" make -j"$(nproc)" &&
        make install
}

compile_libvmaf() {
    echo "Compiling libvmaf"
    cd "$source_dir" &&
        PATH="$bin_dir:$PATH" &&
        wget https://github.com/Netflix/vmaf/archive/v2.3.1.tar.gz && tar xvf v2.3.1.tar.gz &&
        mkdir -p vmaf-2.3.1/libvmaf/build &&
        cd vmaf-2.3.1/libvmaf/build &&
        meson setup -Denable_tests=false -Denable_docs=false --buildtype=release --default-library=static .. --prefix "$install_dir" --bindir="$bin_dir" --libdir="$install_dir/lib" &&
        ninja &&
        ninja install
}

compile_ffmpeg() {
    local file unpack_dir
    file="ffmpeg-snapshot.tar.bz2"
    unpack_dir="ffmpeg"
    cd "$source_dir" &&
        wget -O "$file" https://ffmpeg.org/releases/"$file" &&
        tar xjvf "$file" &&
        cd "$unpack_dir" &&
        PATH="$bin_dir:$PATH" PKG_CONFIG_PATH="$install_dir/lib/pkgconfig" ./configure \
            $@ \
            --prefix="$install_dir" \
            --extra-cflags="-I$install_dir/include" \
            --extra-ldflags="-L$install_dir/lib" \
            --extra-libs="-lpthread -lm" \
            --ld="g++" \
            --bindir="$bin_dir" \
            --enable-gpl \
            --enable-gnutls \
            --enable-libaom \
            --enable-libass \
            --enable-libfdk-aac \
            --enable-libfreetype \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libsvtav1 \
            --enable-libdav1d \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-nonfree &&
        PATH="$bin_dir:$PATH" make -j"$(nproc)" &&
        make install &&
        hash -r
}

dir=$(pwd)

echo "Building ffmpeg"
echo "Source directory: $source_dir"
echo "Install directory: $install_dir"
echo "Static: $static"
echo "Shared: $shared"

echo "Clearing the source and install directories"
rm -rf "$source_dir" || true
rm -rf "$install_dir" || true
mkdir -p "$source_dir" "$bin_dir"

install_dependencies
compile_nasm
compile_x264
compile_x265
compile_libvpx
compile_fdk-aac
compile_libopus
compile_libdav1d
compile_libaom
compile_libsvtav1
compile_libvmaf

if [[ "$static" == true ]]; then
    echo "Building ffmpeg static"
    compile_ffmpeg --pkg-config-flags="--static"
elif [[ "$shared" == true ]]; then
    echo "Building ffmpeg shared"
    compile_ffmpeg --disable-static --enable-shared --pkg-config-flags="--shared"
fi

cd "$dir"
