#!/usr/bin/env bash

set -euxo pipefail

this_dir=$(dirname "$(realpath "${BASH_SOURCE:-$0}")")
usage="$(basename "$0") [-h] [-s, --source-dir] [-p, --prefix] -- Compiles libdrm from source

The packages managers \`apt\` and \`pacman\` are supported.

where:
    -h, --help          show this help text
    -s, --source-dir    libdrm source directory (default: ./libdrm_sources)
    -p, --prefix        libdrm install directory (default: /usr)"

src="./libdrm"
prefix="/usr"
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h | --help)
            echo "$usage"
            exit
            ;;
        -s | --source-dir)
            src="$2"
            shift
            shift
            ;;
        *)
            prefix="$key"
            shift
            ;;
    esac
done

install_dependencies() {
    manager="$("$this_dir/helpers/get-package-manager")"
    "${this_dir}/helpers/${manager}/install-libdrm-deps"
}

build() {
    dir=$(pwd)
    echo "Removing path: $src"
    rm -rf "$src"
    echo "Cd to base dir: $(dirname "$src")"
    cd "$(dirname "$src")"
    echo "Cloning libdrm with output dir: $(basename "$src")"
    git clone https://gitlab.freedesktop.org/mesa/drm.git "$(basename "$src")"
    echo "Cd into: $src"
    cd "$src"
    meson setup builddir/ --prefix="$prefix"
    ninja -C builddir/ 
    sudo ninja -C builddir/ install
    cd "$dir"
}

install_dependencies
build
