#!/usr/bin/env bash
set -euo pipefail

this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
root="$(dirname "$this_dir")"
static=true
shared=false
source_dir="$root/Qt"
install_dir="$root/3rdparty/Qt"
usage="Usage: build-qt [--static] [--shared]

Build Qt with static or shared linking.

Options:
    --static            Build Qt with static linking (default=true)
    --shared            Build Qt with shared linking (default=false)
    -s, --source-dir    Qt source directory (default=$source_dir)
    -i, --install-dir   Qt build directory (default=$install_dir)"

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --static)
            echo "Qt will be built with static linking"
            static=true
            shared=false
            shift
            ;;
        --shared)
            echo "Qt will be built with shared linking"
            static=false
            shared=true
            shift
            ;;
        -s | --source-dir)
            source_dir="$2"
            shift
            shift
            ;;
        -i | --install-dir)
            install_dir="$2"
            shift
            shift
            ;;
        *)
            echo "Unknown option: $key"
            echo "$usage"
            exit 1
            ;;
    esac
done

build-qt-static() {
    echo "Downloading Qt sources"
    rm "$source_dir" -rf || true
    mkdir "$source_dir"
    "$root/scripts/helpers/download-qt" --root "$source_dir" qt.qt6.661.src

    echo "Building Qt with static linking"
    export CC=gcc
    export CXX=g++
    export CFLAGS="-Wall"
    rm "$install_dir" -rf || true
    mkdir "$install_dir"
    src="$source_dir/6.6.1/Src"
    "$src/configure" -release -static -prefix "$install_dir" -submodules qtbase,qtmultimedia,qtwayland -no-pch -no-gstreamer -- -S "$src" -B "$src/build" -Wdev -DFFMPEG_DIR="$root/3rdparty/ffmpeg"
    cmake --build "$src/build"
    cmake --install "$src/build"
}

build-qt-shared() {
    echo "Downloading Qt sources with shared linking"
    rm "$source_dir" -rf || true
    rm "$install_dir" -rf || true
    mkdir "$source_dir"
    mkdir "$install_dir"
    "$root/scripts/helpers/download-qt" --root "$source_dir" qt.qt6.661.gcc_64 qt.qt6.661.addons.qtmultimedia
    cp "$source_dir/6.6.1/gcc_64" "$install_dir" -rf
}

if [[ "$static" = true ]]; then
    build-qt-static
elif [[ "$shared" = true ]]; then
    build-qt-shared
else
    echo "Unknown build type"
    echo "$usage"
    exit 1
fi
