#!/usr/bin/env bash
set -euxo pipefail

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
root="$(dirname "$this_dir")"

echo "Setting up release environment"

# If environment variable QT_INSTALLER_JWT_TOKEN is not set, abort
token="${QT_INSTALLER_JWT_TOKEN:-}"
if [[ -z "$token" ]]; then
    echo "QT_INSTALLER_JWT_TOKEN is not set" >&2
    exit 1
fi

echo "Installing project dependencies"
manager="$("$root/scripts/helpers/get-package-manager")"
"$root/scripts/helpers/${manager}/install-project-deps"

echo "Build Qt with static linking"
"$root/scripts/build-qt-static"

echo "Building project"
"$root/scripts/configure" -- -DBUILD_TESTING=ON
cmake --build ./build --target package

echo "Running tests"
ctest --test-dir "$root/build" --verbose
