name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:

      matrix:
        flag: [--static, --shared]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        env: 
          QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
        run: |
          echo "With flag ${{ matrix.flag }}"
          ./scripts/setup ${{ matrix.flag }}


      - name: Build project
        run: |
          ./scripts/configure -- -DBUILD_TESTING=ON
          cmake --build ./build

      - name: Run test
        run: |
          ctest --test-dir ./build --verbose
