name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:

      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        flag: [--static, --shared]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        env: 
          QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "With flag ${{ matrix.flag }}"
          ./scripts/setup ${{ matrix.flag }}


      - name: Build project
        run: |
          ./scripts/configure -- -DBUILD_TESTING=ON
          cmake --build ./build

      - name: Run test
        run: |
          ctest --test-dir ./build --verbose
