name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:

      matrix:
        flag: [--static, --shared]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        env: 
          QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
        run: |
          echo "With flag ${{ matrix.flag }}"
          ./scripts/setup ${{ matrix.flag }}


      - name: Build project
        run: |
          ./scripts/configure -- -DBUILD_TESTING=ON
          cmake --build ./build --target package
          sudo cmake --install ./build

      - name: Run ctest
        run: |
          ctest --test-dir ./build --verbose

      - name: Run installed tests
        run: |
          /opt/snapshot/snapshot_tests

      - name: Run test tarball
        run: |
          tar -xvf ./build/snapshot-*.tar.gz -C /tmp
          /tmp/snapshot-*/run_tests
